### ISSUE TITLE
Replace catchError() with Chai .throws()

### ISSUE THREAD

**Issue by jameshopkins** [sjltaylor/stats-gopher-js#2]

**Comment by s6577t** [comment]
PR? ... go on ...

**Comment by jameshopkins** [comment]
https://github.com/sjltaylor/stats-gopher-js/pull/3 :)

**Comment by jameshopkins** [comment]
In fact, we should probably improve on this further, and throw `TypeError`s instead for these scenarios. We can then check them in a stricter sense using `expect(fn).to.not.throw(new TypeError(message));`. Wait a sec, and I'll change this.

**Comment by s6577t** [comment]
Haha, too late.

**Comment by jameshopkins** [comment]
Fixed by https://github.com/sjltaylor/stats-gopher-js/pull/3
